name: drivergoo
description: "Ghumo Partner - A driver app for ride-sharing services. Complete trips, earn money, and manage your driving business efficiently."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  path_provider: ^2.1.2
  http: ^1.2.1
  jwt_decoder: ^2.0.1

  firebase_core: ^3.8.1      # core
  firebase_auth: ^5.3.3      # auth
  firebase_messaging: 15.2.10
   
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.5.0
  intl: ^0.20.2
  geolocator: ^11.0.0
  # Upgraded to latest with Android 12+ scoped storage support
  image_picker: ^1.1.2
  firebase_analytics: ^11.6.0
  google_fonts: ^6.1.0
  socket_io_client: ^3.1.2
  audioplayers: ^5.2.1
  url_launcher: ^6.2.6
  flutter_background_service: ^5.0.5
  wakelock_plus: ^1.2.0
  flutter_local_notifications: ^17.0.0
  google_mlkit_text_recognition: ^0.11.0
  shared_preferences: ^2.2.2
  upi_payment_qrcode_generator: ^1.2.1
  cupertino_icons: ^1.0.8
  razorpay_flutter: ^1.4.0
  http_parser: ^4.1.2
  lottie: ^3.1.0 
  android_intent_plus: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/bike_pencil.json
    - assets/sounds/notification.mp3
    - assets/default_avatar.png
    - assets/images/mobile.png
    - assets/images/logo.png
    - assets/images/logo1.png   # 👈 your orange scooter logo
    - assets/images/banner_profile.png
    - assets/images/ghumo_partner_rider.png
flutter_native_splash:
  android: true
  ios: false
  web: false

  # Background color
  color: "#F5F7FA"

  # Logo for Android 11 and below
  image: assets/images/logo.png

  # Android 12 configuration
  android_12:
    # Same background
    color: "#F5F7FA"

    # Use the same logo (Android will auto circle-crop it)
    image: assets/images/logo1.png

    icon_background_color: "#F5F7FA"

  fullscreen: true
